- name: Update package list
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - git
      - docker.io
      - curl
    state: present

- name: Install or upgrade Docker Compose
  shell: |
    mkdir -p /usr/local/lib/docker/cli-plugins
    curl -SL https://github.com/docker/compose/releases/download/v2.24.2/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
    sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
    docker compose version
  args:
    creates: /usr/local/bin/docker-compose

- name: Add user to the Docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes
